

const newsList = [
  {month: "Dec", year: "2023", news: "Allison Tossounian completes her Undergraduate Research Study in our lab. Congratulations, Allison!"},
  {month: "Dec", year: "2023", news: "Our work in collaboration with the Rice team on Terahertz Cavity Magnon Polaritons has been published in <a href='https://doi.org/10.1002/adom.202302270' style='color:#3b82f6;'>Advanced Optical Materials</a>."},
  {month: "Apr", year: "2023", news: "Our comprehensive study on controlling magnon processes in 0D systems has been published in <a href='https://journals.aps.org/prapplied/abstract/10.1103/PhysRevApplied.19.044087' style='color:#3b82f6;'>Phys. Rev. Appl.</a>."},
  {month: "Feb", year: "2023", news: "Arezoo defends her PhD thesis and joins Western Digital. Congratulations, Arezoo!"},
  {month: "Jan", year: "2023", news: "We welcome Trevin Lee and Alex Hernandez as undergraduate researchers to our lab."},
  {month: "Oct", year: "2022", news: "Our lab and the Dept of Physics and Astronomy at this year's <a href='https://physics.ucr.edu/news/2022/10/21/physics-and-astronomy-night-art-and-innovation-downtown-riverside' style='color:#3b82f6;'>Long Night of Arts and Innovations</a>. Our students inspire and educate hundreds of kids and adults in downtown Riverside."},
  {month: "Sep", year: "2022", news: "We welcome Audrey Ng and Sasha Korotneva to our group!"},
  {month: "Aug", year: "2022", news: "How to tweak the 'good old' FMR equations to describe inertial spin dynamics. Our collaborative paper is published in <a href='https://doi.org/10.1103/PhysRevB.106.054428' style='color:#3b82f6;'>Phys. Rev. B</a>."},
  {month: "Aug", year: "2022", news: "Magnon transport across AFM/FM interface leads to robust spin injection up to room temperature. Rudy's paper is published in <a href='https://doi.org/10.1103/PhysRevResearch.4.033139' style='color:#3b82f6;'>Phys. Rev. Research</a>."},
  {month: "Aug", year: "2022", news: "Arezoo and Rudy present their posters at the <a href='https://magnonics.us/' style='color:#3b82f6;'>Magnonics 2022 conference</a> in Oxnard, CA."},
  {month: "Aug", year: "2022", news: "Prof. Barsukov organizes and chairs the 7th International Conference on Magnonics in Oxnard, CA with 100 attendees from all over the world. More information at <a href='https://magnonics.us/' style='color:#3b82f6;'>magnonics.us</a>. Arezoo, Rudy, Shirash, Rundong take active part on the local organizing committee."},
  {month: "Jun", year: "2022", news: "Diego, Travis, and Henry graduate with BSc in Physics. Congratulations!"},
  {month: "Jun", year: "2022", news: "Allison receives Outstanding 2nd Year Undergraduate Award. Congratulations!"},
  {month: "May", year: "2022", news: "Prof. Barsukov delivers an invited talk at the 11th Spin-Caloritronics conference at UI Urbana-Champaign on spin-torque susceptibility in nonlinear magnetic systems."},
  {month: "May", year: "2022", news: "Prof. Barsukov delivers an invited Condensed Matter Seminar at UC Los Angeles on spin currents in antiferromagnetic heterostructures."},
  {month: "May", year: "2022", news: "Shirash passes his Oral Qualifying Exam. Congratulations!"},
  {month: "May", year: "2022", news: "Shirash receives the Outstanding Teaching Assistant Award from the Graduate Division. Congratulations!"},
  {month: "Apr", year: "2022", news: "Arezoo receives the DYP Award. Congratulations!"},
  {month: "Mar", year: "2022", news: "Rudy receives the DYP Award. Congratulations!"},
  {month: "Mar", year: "2022", news: "Prof. Barsukov presents an invited talk on spin dynamics in zero-dimensional systems at the APS March Meeting in Chicago, IL."},
  {month: "Mar", year: "2022", news: "Rudy, Arezoo, and Shirash present their talks at the APS March Meeting in Chicago, IL."},
  {month: "Jan", year: "2022", news: "Arezoo Etesamirad and Shirash Regmi present their talks at the MMM conference in New Orleans, LA."},
  {month: "Dec", year: "2021", news: "Arezoo Etesamirad wins the IEEE Magnetics Society Travel Award. Congratulations!"},
  {month: "Nov", year: "2021", news: "Our collaborative paper on damping and tunable magnetic anisotropy by strain in EuIG has been accepted in <a href='https://doi.org/10.1103/PhysRevMaterials.5.124414' style='color:#3b82f6;'>Phys. Rev. Mater.</a>."},
  {month: "Oct", year: "2021", news: "Prof. Barsukov gives an invited seminar on 'Interplay of nonlinearities and spin-torque' at the Online Spintronics Seminars <a href='https://spintalk.org/' style='color:#3b82f6;'>spintalk.org</a>."},
  {month: "Sep", year: "2021", news: "Rodolfo Rodriquez receives the GAANN fellowship. Congratulations, Rudy!"},
  {month: "Aug", year: "2021", news: "Prof. Barsukov delivers an invited talk at the SPIE conference."},
  {month: "Aug", year: "2021", news: "Prof. Barsukov and Rodolfo Rodriguez are visiting Helmholtz-Center Dresden-Rossendorf."},
  {month: "Aug", year: "2021", news: "Prof. Barsukov and Rodolfo Rodriguez are carrying out experiment at the University Duisburg-Essen, Germany."},
  {month: "Jul", year: "2021", news: "Shirash Regmi receives Al Staats Award for constructing low-temperature microwave spectrometer. Congratulations, Shirash!"},
  {month: "Jul", year: "2021", news: "Arezoo Etesamirad receives Provost’s Scholar for the Advancement of Physical Sciences Fellowship. Congratulations, Arezoo!"},
  {month: "Jun", year: "2021", news: "Arezoo Etesamirad receives the Outstanding Teaching Assistant Award 2020-2021 from the Department of Physics and Astronomy. Congratulations!"},
  {month: "May", year: "2021", news: "Prof. Barsukov delivers an invited colloquium at the Technical University Darmstadt and University Duisburg-Essen, Germany for the research center CRC 270 HoMMage."},
  {month: "Apr", year: "2021", news: "Arezoo Etesamirad receives the UCR Outstanding Teaching Assistant Award 2020-2021. Congratulations!"},
  {month: "Apr", year: "2021", news: "Our paper on controlling magnon interaction by a nanoscale switch has been published in <a href='https://doi.org/10.1021/acsami.1c01562' style='color:#3b82f6;'>ACS Appl. Mater. Interfaces</a>."},
  {month: "Apr", year: "2021", news: "Our paper on self-stabilizing spin transport by winding spin textures has been published in <a href='https://link.aps.org/doi/10.1103/PhysRevB.103.144412' style='color:#3b82f6;'>Phys. Rev. B</a>."},
  {month: "Mar", year: "2021", news: "Arezoo Etesamirad delivers a talk at the APS March Meeting on Controlling Magnon Interaction in nanomagnets."},
  {month: "Jan", year: "2021", news: "Prof. Barsukov delivers an invited talk at the 3D MAGiC Workshop for the Research Center Juelich, Germany."},
  {month: "Dec", year: "2020", news: "Arezoo Etesamirad receives APS student travel award. Congratulations!"},
  {month: "Nov", year: "2020", news: "<a href='https://phys.org/news/2023-05-manual-dynamics-nanomagnets.html' style='color:#3b82f6;'>Prof. Barsukov delivers an invited talk at the IEEE International Conference on 'Nanomaterials: Applications & Properties'.</a>"},
  {month: "Sep", year: "2020", news: "<a href='https://news.ucr.edu/articles/2019/12/05/simple-experiment-explains-magnetic-resonance' style='color:#3b82f6;'>Prof. Barsukov delivers an invited talk at the SPIE conference.</a>"},
  {month: "Aug", year: "2020", news: "Prof. Barsukov delivers a talk at The 31st Magnetic Recording Conference."},
  {month: "Jul", year: "2020", news: "Our home-made high-field low-temperature microwave spectrometer goes online."},
  {month: "Jul", year: "2020", news: "Joshua Bocanegra receives UCR's CAMP Scholarship. Congratulations!"},
  {month: "Jul", year: "2020", news: "Bassim Arkook defends his dissertation Spin Dynamics in Two-Magnet Systems and receives PhD degree. Congratulations, Dr. Arkook!"},
  {month: "Jun", year: "2020", news: "Erik Hagen receives the Outstanding Senior Undergraduate Student Award. Congratulations!"},
  {month: "Jun", year: "2020", news: "Erik Hagen, Ethan Jarquin, Grace Dodgen, Tyler Smith receive their BSc degrees at the graduation ceremony. Congratulations!"},
  {month: "Jun", year: "2020", news: "Tyler Smith receives the Outstanding Senior Undergraduate Student Award and the NSF Graduate Research Fellowship. Congratulations!"},
  {month: "Jun", year: "2020", news: "Erik Hagen receives the Outstanding Senior Undergraduate Student Award. Congratulations!"},
  {month: "May", year: "2020", news: "Prof. Barsukov delivers an invited talk for the Academy of Distinguished Teachers at UCR."},
  {month: "May", year: "2020", news: "The collaborative paper on freestanding microwave antenna devices has been published in <a href='https://doi.org/10.1103/PhysRevApplied.13.054009' style='color:#3b82f6;'>Phys. Rev. Appl.</a>."},
  {month: "Mar", year: "2020", news: "The META2020 symposium where Prof. Barsukov was invited to give a talk on nonlinear spin dynamics in nanomagnets is postponed until further notice due to COVID-19."},
  {month: "Mar", year: "2020", news: "Our SHINES-collaborative paper on SAF-based spin Josephson oscillator is published in <a href='https://doi.org/10.1063/5.0003477' style='color:#3b82f6;'>Appl. Phys. Lett.</a>."},
  {month: "Mar", year: "2020", news: "The Intermag in Montreal where Prof. Barsukov was invited to give a talk on nonlinear spin dynamics in nanomagnets is cancelled due to COVID-19."},
  {month: "Feb", year: "2020", news: "Prof. Barsukov delivers an invited talk at the Center for Memory and Recording Research, UC San Diego."},
  {month: "Feb", year: "2020", news: "Prof. Barsukov attends the award ceremony as UCR's Junior Excellence in Teaching Distinguished faculty."},
  {month: "Jan", year: "2020", news: "Prof. Barsukov delivers an invited talk at the Condensed Matter Seminar (dept of physics), UC San Diego."},
  {month: "Dec", year: "2019", news: "Our educational paper on magnetic resonance is published in <a href='https://doi.org/10.1119/1.5135797' style='color:#3b82f6;'>The Physics Teacher</a>."},
  {month: "Nov", year: "2019", news: "Our lab visits the Partiot high-school of Jurupa Valley with demonstration experiments on magnetism and spintronics."},
  {month: "Nov", year: "2019", news: "Students from the Palms AVID high-school visit our lab to learn about magnetism and spintronics."},
  {month: "Nov", year: "2019", news: "The paper on 'Resonant non-linear damping in nanomagnets' is featured in 'UCR Life'."},
  {month: "Nov", year: "2019", news: "Bassim Arkook presents a talk on 'Microwave Spectroscopy of Individual FM/2D Microstructures' at the MMM conference in Las Vegas. David Nelson presents a poster on 'Exploring Magnetic Resonance with a Compass'. Prof. Barsukov serves as a member of the Program Committee."},
  {month: "Oct", year: "2019", news: "Magnon scattering redefines how nanomagnets respond to spin currents. A study on resonant non-linear spin response in nanoscale magnets has been published in <a href='https://phys.org/news/2019-10-small-magnets-reveal-big-secrets.html' style='color:#3b82f6;'>Science Advances</a>."},
  {month: "Oct", year: "2019", news: "Prof. Barsukov delivers a talk on long-range spin transport at SHINES All-Hands Meeting."},
  {month: "Oct", year: "2019", news: "Prof. Barsukov delivers a physics colloquium at the California State University Long Beach."},
  {month: "Oct", year: "2019", news: "Our lab represents the Dept of Physics and Astronomy at this year's Long Night of Arts and Innovations. Students from our group and Astro Club, and Development Technicians inspire and educate hundreds of kids and adults in downtown Riverside."},
  {month: "Sep", year: "2019", news: "David and Keanu appear on the postcard of UCR Physics Program."},
  {month: "Aug", year: "2019", news: "David Nelson and Stephen Iota graduate as BSc (Physics) from our lab. Congratulations!"},
  {month: "Aug", year: "2019", news: "Prof. Barsukov delivers an invited talk at the SPIE Spintronics conference in San Diego, CA."},
  {month: "Aug", year: "2019", news: "Prof. Barsukov delivers a talk at EFRC review with the US Department of Energy in Washington DC. Arezoo and Rudy present our research with two posters."},
  {month: "Jun", year: "2019", news: "We provide lab tours and present demonstration experiments developed in our lab to local teachers of the Physics Teacher Academy."},
  {month: "Jun", year: "2019", news: "Prof. Barsukov receives 'Junior Excellence in Teaching Award' by the Academy of Distinguished Teachers, UCR."},
  {month: "Jun", year: "2019", news: "David Nelson receives Brown Williams Undergraduate Award for Outstanding Achievements."},
  {month: "May", year: "2019", news: "Prof. Barsukov delivers an invited talk at the Southern California Condensed Matter Meeting, USC, Los Angeles."},
  {month: "Mar", year: "2019", news: "Prof. Barsukov receives the recognition as outstanding referee by Communications Physics."},
  {month: "Mar", year: "2019", news: "David Nelson's poster presented at the annual SHINES meeting by Arezoo Etesamirad receives a best poster award (3rd place)."},
  {month: "Mar", year: "2019", news: "Prof. Barsukov delivers a talk at the annual meeting of the SHINES research center."},
  {month: "Mar", year: "2019", news: "Prof. Barsukov delivers a physics colloquium at the University of Wyoming in Laramie."},
  {month: "Mar", year: "2019", news: "Prof. Barsukov delivers a physics colloquium at the University of Alabama in Tuscaloosa."},
  {month: "Mar", year: "2019", news: "Prof. Barsukov delivers a condensed matter seminar at University of Delaware."},
  {month: "Jan", year: "2019", news: "Prof. Barsukov delivers a talk on micro-scale microwave spectroscopy at the SHINES All-hands meeting."},
  {month: "Jan", year: "2019", news: "Hassan Al-Ghamdi and Abdulrahman Al-Bariqi graduate with MSc in Physics. Congratulations!"},
  {month: "Jan", year: "2019", news: "Prof. Barsukov delivers a talk on exchange-mediated spin flows at the Joint Intermag-MMM 2019 Conference in Washington D.C."},
  {month: "Jan", year: "2019", news: "Prof. Barsukov accepts an invitation to serve on the program committee for the MMM 2019 conference in Las Vegas, NV."},
  {month: "Dec", year: "2018", news: "Prof. Barsukov delivers an invited seminar on magnon condensates and spin superfluidity at University Duisburg-Essen, Germany."},
  {month: "Dec", year: "2018", news: "Prof. Barsukov gives a series of invited lectures on magnetism at University Duisburg-Essen, Germany."},
  {month: "Nov", year: "2018", news: "Bassim Arkook delivers a talk on spin dynamics in coupled spin systems at the SHINES seminar."},
  {month: "Sept", year: "2018", news: "Our lab receives the collaborative DoE-EFRC grant 'Spins and Heat in Nanoscale Electronic Systems'."},
  {month: "Sept", year: "2018", news: "Prof. Barsukov has been elected to Divisional Executive Committee MIND of the American Vacuum Society."},
  {month: "Sept", year: "2018", news: "Prof. Barsukov delivers an invited seminar talk at the Nijmegen University, Netherlands."},
  {month: "Sept", year: "2018", news: "Prof. Barsukov is on a research stay at the University Duisburg-Essen and Helmholtz Research Center Dresden, Germany."},
  {month: "Aug", year: "2018", news: "Our lab receives NSF grant 'Spin torque devices driven by tailored spin currents'."},
  {month: "Jul", year: "2018", news: "Prof. Barsukov delivers an invited symposium talk at the Intl Conference on Magnetism in San Francisco, CA."},
  {month: "Jun", year: "2018", news: "Erik Hagen joins our group as Undergraduate Student Researcher."},
  {month: "Jun", year: "2018", news: "Prof. Barsukov delivers an invited talk at the Spin Caloritronics conference in Columbus, OH."},
  {month: "Jun", year: "2018", news: "Our team presents demonstration experiments on magnetism and spintronics for the Summer Teacher Academy."},
  {month: "Jun", year: "2018", news: "Esther Cookson graduates with BSc in physics. Congratulations!"},
  {month: "Apr", year: "2018", news: "Highlander Day at UCR: Prof. Barsukov presents Condensed Matter Research and gives lab tours."},
  {month: "Mar", year: "2018", news: "Stephen Iota joins our lab as Undergraduate Student Researcher."},
  {month: "Mar", year: "2018", news: "Bassim Arkook delivers a talk at the APS March Meeting on magnon condensation in coupled spin systems."},
  {month: "Jan", year: "2018", news: "Bassim Arkook receives the APS Student Travel Award."},
  {month: "Dec", year: "2017", news: "Prof. Barsukov delivers an invited seminar on magnetism at the Teacher Academy Workshop."},
  {month: "Nov", year: "2017", news: "Bassim Arkook delivers a talk at the Magnetism and Magnetic Materials Conference on YIG/Py spin-torque oscillator nanodevices."},
  {month: "Oct", year: "2017", news: "Discover Day at UCR: Esther Cookson develops and our group presents an outreach program to the public."},
  {month: "Oct", year: "2017", news: "Esther Cookson develops and our group presents an outreach program at the Long Night of Arts and Innovations in Riverside Downtown. Hundreds of visitors are excited to see demonstration experiments on electromagnetism and spintronics. Our group receives a thank-you letter from the Mayor of Riverside."},
  {month: "Sep", year: "2017", news: "Bassim Arkook receives a Student Travel Award of the IEEE Magnetics Society."},
  {month: "Jun", year: "2017", news: "Rodolfo Rodriguez graduates as BSc (physics)."}
];



export {newsList}