
const publicationsArray = [
        
    {
        Title: "Terahertz cavity magnon polaritons",
        People: ["T.E. Kritzell", "A. Baydin", "Fuyang Tay", "R. Rodriguez", "Hiroyuki Nojiri", "H.O. Everitt", "I. Barsukov", "Junichiro Kono"],
        Journal: "Adv. Opt. Mater. 2302270 (2023)",
        DOI: "doi.org/10.1002/adom.202302270",
        BibTex: null,
        Citation: null,
    },
    {
        Title: "Controlling selection rules for magnon scattering in nanomagnets by spatial symmetry breaking",
        People: ["Arezoo Etesamirad", "Julia Kharlan", "Rodolfo Rodriguez", "Igor Barsukov", "Roman Verba"],
        Journal: "Phys. Rev. Appl. 19, 044087 (2023)",
        DOI: "doi.org/10.1103/PhysRevApplied.19.044087",
        BibTex: `@article{https://doi.org/10.1002/adom.202302270, 
        author = {Kritzell, T. Elijah and Baydin, Andrey and Tay, Fuyang and Rodriguez, Rodolfo and Doumani, Jacques and Nojiri, Hiroyuki and Everitt, Henry O. and Barsukov, Igor and Kono, Junichiro}, 
        title = {Terahertz Cavity Magnon Polaritons}, 
        journal = {Advanced Optical Materials}, 
        volume = {12}, 
        number = {10}, 
        pages = {2302270}, 
        keywords = {antiferromagnet, magnon polaritons, Strong Coupling}, 
        doi = {https://doi.org/10.1002/adom.202302270}, 
        url = {https://onlinelibrary.wiley.com/doi/abs/10.1002/adom.202302270}, 
        eprint = {https://onlinelibrary.wiley.com/doi/pdf/10.1002/adom.202302270}, 
        abstract = {Abstract Hybrid light–matter coupled states, or polaritons, in magnetic materials have attracted significant attention due to their potential for enabling novel applications in spintronics and quantum information processing. However, most magnon-polariton studies in the strong coupling regime to date have been carried out for ferromagnetic materials with magnon excitations at gigahertz frequencies. Here, strong resonant photon–magnon coupling at frequencies above 1 terahertz is investigated for the first time in a prototypical room-temperature antiferromagnetic insulator, NiO, inside a Fabry–Pérot cavity. The cavity is formed by the crystal itself with a thickness adjusted to an optimal value. Terahertz time-domain spectroscopy measurements in magnetic fields up to 25 T reveal the evolution of the magnon frequency through Fabry–Pérot cavity modes with photon–magnon anticrossing behavior, demonstrating clear vacuum Rabi splittings exceeding the polariton linewidths. These results show that NiO is a promising platform for exploring antiferromagnetic spintronics and cavity magnonics in the terahertz frequency range.}, year = {2024} 
        } `,
        Citation: null,
    },
    {
        Title: "Robust spin injection via thermal magnon pumping in antiferromagnet/ferromagnet hybrid systems",
        People: ["Rodolfo Rodriguez", "Shirash Regmi", "Hantao Zhang", "Wei Yuan", "Pavlo Makushko", "Eric A. Montoya", "Ihor Veremchuk", "René Hübner", "Denys Makarov", "Jing Shi", "Ran Cheng", "Igor Barsukov"],
        Journal: "Phys. Rev. Res. 4, 033139 (2022)",
        DOI: "doi.org/10.1103/PhysRevResearch.4.033139",
        BibTex: `@article{PhysRevApplied.19.044087, 
        title = {Controlling Selection Rules for Magnon Scattering in Nanomagnets by Spatial Symmetry Breaking}, 
        author = {Etesamirad, Arezoo and Kharlan, Julia and Rodriguez, Rodolfo and Barsukov, Igor and Verba, Roman}, 
        journal = {Phys. Rev. Appl.}, 
        volume = {19}, 
        issue = {4}, 
        pages = {044087}, 
        numpages = {15}, 
        year = {2023},
        month = {Apr}, 
        publisher = {American Physical Society}, 
        doi = {10.1103/PhysRevApplied.19.044087}, 
        url = {https://link.aps.org/doi/10.1103/PhysRevApplied.19.044087} 
        } 
        `,
        Citation: null,
    },
    {
        Title: "Theory of inertial spin dynamics in anisotropic ferromagnets",
        People: ["Mikhail Cherkasskii", "Igor Barsukov", "Ritwik Mondal", "Michael Farle", "Anna Semisalova"],
        Journal: "Phys. Rev. B 106, 054428 (2022)",
        DOI: "doi.org/10.1103/PhysRevB.106.054428",
        BibTex: `@article{PhysRevResearch.4.033139, 
        title = {Robust spin injection via thermal magnon pumping in antiferromagnet/ferromagnet hybrid systems}, 
        author = {Rodriguez, Rodolfo and Regmi, Shirash and Zhang, Hantao and Yuan, Wei and Makushko, Pavlo and Montoya, Eric A. and Veremchuk, Ihor and H\"ubner, Ren\'e and Makarov, Denys and Shi, Jing and Cheng, Ran and Barsukov, Igor}, 
        journal = {Phys. Rev. Res.}, 
        volume = {4}, 
        issue = {3}, 
        pages = {033139}, 
        numpages = {8}, 
        year = {2022}, 
        month = {Aug}, 
        publisher = {American Physical Society}, 
        doi = {10.1103/PhysRevResearch.4.033139}, 
        url = {https://link.aps.org/doi/10.1103/PhysRevResearch.4.033139} 
        } 
        `,
        Citation: null,

    },
    {
        Title: "First and second order magnetic anisotropy and damping of europium iron garnet under high strain",
        People: ["V.H. Ortiz", "B. Arkook", "Junxue Li", "M. Aldosary", "M. Biggerstaff", "Wei Yuan", "C. Warren", "Yasuhiro Kodera", "J.E. Garay", "I. Barsukov", "Jing Shi"],
        Journal: "Phys. Rev. Mater. 5, 124414 (2021)",
        DOI: "doi.org/10.1103/PhysRevMaterials.5.124414",
        BibTex: `@article{PhysRevMaterials.5.124414, 
        title = {First- and second-order magnetic anisotropy and damping of europium iron garnet under high strain}, 
        author = {Ortiz, V\'{\i}ctor H. and Arkook, Bassim and Li, Junxue and Aldosary, Mohammed and Biggerstaff, Mason and Yuan, Wei and Warren, Chad and Kodera, Yasuhiro and Garay, Javier E. and Barsukov, Igor and Shi, Jing}, 
        journal = {Phys. Rev. Mater.}, 
        volume = {5}, 
        issue = {12}, 
        pages = {124414}, 
        numpages = {7}, 
        year = {2021}, 
        month = {Dec}, 
        publisher = {American Physical Society}, 
        doi = {10.1103/PhysRevMaterials.5.124414}, 
        url = {https://link.aps.org/doi/10.1103/PhysRevMaterials.5.124414} 
        }
        `,
        Citation: null,
    },
    {
        Title: "Controlling magnon interaction by a nanoscale switch",
        People: ["A. Etesamirad", "R. Rodriguez", "J. Bocanegra", "R. Verba", "J. Katine", "I.N. Krivorotov", "V. Tyberkevych", "B. Ivanov", "I. Barsukov"],
        Journal: "ACS Appl. Mater. Interfaces 13, 20288 (2021)",
        DOI: "doi.org/10.1021/acsami.1c01562",
        BibTex: `@article{https://doi.org/10.1002/adom.202302270, 
        author = {Kritzell, T. Elijah and Baydin, Andrey and Tay, Fuyang and Rodriguez, Rodolfo and Doumani, Jacques and Nojiri, Hiroyuki and Everitt, Henry O. and Barsukov, Igor and Kono, Junichiro}, 
        title = {Terahertz Cavity Magnon Polaritons}, 
        journal = {Advanced Optical Materials}, 
        volume = {12}, 
        number = {10}, 
        pages = {2302270}, 
        keywords = {antiferromagnet, magnon polaritons, Strong Coupling}, doi = {https://doi.org/10.1002/adom.202302270}, 
        url = {https://onlinelibrary.wiley.com/doi/abs/10.1002/adom.202302270}, eprint = {https://onlinelibrary.wiley.com/doi/pdf/10.1002/adom.202302270}, abstract = {Abstract Hybrid light–matter coupled states, or polaritons, in magnetic materials have attracted significant attention due to their potential for enabling novel applications in spintronics and quantum information processing. However, most magnon-polariton studies in the strong coupling regime to date have been carried out for ferromagnetic materials with magnon excitations at gigahertz frequencies. Here, strong resonant photon–magnon coupling at frequencies above 1 terahertz is investigated for the first time in a prototypical room-temperature antiferromagnetic insulator, NiO, inside a Fabry–Pérot cavity. The cavity is formed by the crystal itself with a thickness adjusted to an optimal value. Terahertz time-domain spectroscopy measurements in magnetic fields
        up to 25 T reveal the evolution of the magnon frequency through Fabry–Pérot cavity modes with photon–magnon anticrossing behavior, demonstrating clear vacuum Rabi splittings exceeding the polariton linewidths. These results show that NiO is a promising platform for exploring antiferromagnetic spintronics and cavity magnonics in the terahertz frequency range.}, 
        year = {2024} 
        }
        `,
        Citation: null,
    },
    {
        Title: "Self-stabilizing exchange-mediated spin transport",
        People: ["T. Schneider", "D. Hill", "A. Kakay", "K. Lenz", "J. Lindner", "J. Fassbender", "P. Upadhyaya", "Yuxiang Liu", "Kang Wang", "Y. Tserkovnyak", "I. N. Krivorotov", "I. Barsukov"],
        Journal: "Phys. Rev. B 103, 144412 (2021)",
        DOI: "doi.org/10.1103/PhysRevB.103.144412",
        BibTex: `@article{PhysRevB.103.144412, 
        title = {Self-stabilizing exchange-mediated spin transport}, 
        author = {Schneider, T. and Hill, D. and K\'akay, A. and Lenz, K. and Lindner, J. and Fassbender, J. and Upadhyaya, P. and Liu, Yuxiang and Wang, Kang and Tserkovnyak, Y. and Krivorotov, I. N. and Barsukov, I.}, 
        journal = {Phys. Rev. B}, 
        volume = {103}, 
        issue = {14}, 
        pages = {144412}, 
        numpages = {7}, 
        year = {2021}, 
        month = {Apr}, 
        publisher = {American Physical Society}, 
        doi = {10.1103/PhysRevB.103.144412}, 
        url = {https://link.aps.org/doi/10.1103/PhysRevB.103.144412} 
        }
        `,
        Citation: null
    },
    {
        Title: "Inversion of the Spin-Torque Effect in MTJs Via Resonant Magnon Scattering",
        People: ["I. Barsukov", "H.K. Lee", "A.A. Jara", "Y.-J. Chen", "A.M. Gonçalves", "C. Sha", "J.A. Katine", "R.E. Arias", "B.A. Ivanov", "I.N. Krivorotov"],
        Journal: "2020 IEEE 31st Magnetic Recording Conference (TMRC) 1-2 (2020)",
        DOI: "doi.org/10.1109/TMRC49521.2020.9366713",
        BibTex: `@INPROCEEDINGS{9366713, 
        author={BARSUKOV, Igor and LEE, Han Kyu and JARA, Alejandro A. and CHEN, Yu-Jin and GONÇALVES, Alexandre M. and SHA, Chengcen and KATINE, Jordan A. and ARIAS, Rodrigo E. and IVANOV, Boris A. and KRIVOROTOV, Ilya N.}, 
        booktitle={2020 IEEE 31st Magnetic Recording Conference (TMRC)}, 
        title={Inversion of the Spin-Torque Effect in Mtjs Via Resonant Magnon Scattering}, year={2020}, 
        volume={}, 
        number={}, 
        pages={1-2}, 
        keywords={Damping;Torque;Magnetomechanical effects;Magnetic resonance;Oscillators;Magnetic tunneling;Magnetic recording}, 
        doi={10.1109/TMRC49521.2020.9366713}
        }
        `,
        Citation: null
    },
    {
        Title: "Resonant nonlinear damping in nanoscale magnets",
        People: ["I. Barsukov"],
        Journal: "Proc. SPIE 11470, Spintronics XIII 1147033 (2020)",
        DOI: "doi.org/10.1117/12.2567191",
        BibTex: `@inproceedings{10.1117/12.2567191, 
        author = {Igor Barsukov}, 
        title = {{Resonant nonlinear damping in nanoscale magnets}}, 
        volume = {11470}, 
        booktitle = {Spintronics XIII}, 
        editor = {Henri-Jean M. Drouhin and Jean-Eric Wegrowe and Manijeh Razeghi}, organization = {International Society for Optics and Photonics}, 
        publisher = {SPIE}, 
        pages = {1147033}, 
        keywords = {magnon, nonlinear, spin dynamics, spin torque, damping}, 
        year = {2020}, 
        doi = {10.1117/12.2567191}, 
        URL = {https://doi.org/10.1117/12.2567191} 
        } `,
        Citation: null
    },
    {
        Title: "Free-standing and positionable microwave antenna device for magneto-optical spectroscopy experiments",
        People: ["T. Hache", "M. Vanatka", "L. Flajsman", "T. Weinhold", "T. Hula", "O. Ciubotariu", "M. Albrecht", "B. Arkook", "I. Barsukov", "L. Fallarino", "O. Hellwig", "J. Fassbender", "M. Urbanek", "H. Schultheiss"],
        Journal: "Phys. Rev. Appl. 13, 054009 (2020)",
        DOI: "doi.org/10.1103/PhysRevApplied.13.054009",
        BibTex: `@article{PhysRevApplied.13.054009, 
        title = {Freestanding Positionable Microwave-Antenna Device for Magneto-Optical Spectroscopy Experiments}, 
        author = {Hache, T. and Va\ifmmode \check{n}\else \v{n}\fi{}atka, M. and Flaj\ifmmode \check{s}\else \v{s}\fi{}man, L. and Weinhold, T. and Hula, T. and Ciubotariu, O. and Albrecht, M. and Arkook, B. and Barsukov, I. and Fallarino, L. and Hellwig, O. and Fassbender, J. and Urb\'anek, M. and Schultheiss, H.}, 
        journal = {Phys. Rev. Appl.}, 
        volume = {13}, 
        issue = {5}, 
        pages = {054009}, 
        numpages = {10}, 
        year = {2020}, 
        month = {May}, 
        publisher = {American Physical Society}, 
        doi = {10.1103/PhysRevApplied.13.054009}, 
        url = {https://link.aps.org/doi/10.1103/PhysRevApplied.13.054009} 
        }
        `,
        Citation: null
    },
    {
        Title: "Synthetic antiferromagnet-based spin Josephson oscillator",
        People: ["Yizhou Liu", "Igor Barsukov", "Ilya Krivorotov", "Yafis Barlas", "Roger K. Lake"],
        Journal: "Appl. Phys. Lett. 116, 132409 (2020)",
        DOI: "doi.org/10.1063/5.0003477",
        BibTex: `@article{10.1063/5.0003477, 
        author = {Liu, Yizhou and Barsukov, Igor and Barlas, Yafis and Krivorotov, Ilya N. and Lake, Roger K.}, 
        title = "{Synthetic antiferromagnet-based spin Josephson oscillator}", 
        journal = {Applied Physics Letters},
        volume = {116}, 
        number = {13}, 
        pages = {132409}, 
        year = {2020}, 
        month = {04}, 
        abstract = "{Two easy-plane ferromagnetic layers, antiferromagnetically coupled through a thin nonmagnetic metal layer, form the magnetic analog of a Josephson junction. A current driven spin chemical potential drives a 2π precession of the in-plane magnetization of each ferromagnet. The participation of the full magnetic moment in the 2π precession maximizes the giant magnetoresistance and the ac output power. The frequency can be continuously tuned by a dc bias. An applied ac bias results in a time-averaged magnetoresistance with Shapiro-like steps. The multistate mode-locking behavior exhibited by the Shapiro steps may be exploited for applications such as microwave detectors and neuromorphic computing. They may also serve as an experimental signature of spin superfluidity.}", 
        issn = {0003-6951}, 
        doi = {10.1063/5.0003477}, 
        url = {https://doi.org/10.1063/5.0003477}, 
        eprint = 
        {https://pubs.aip.org/aip/apl/article-pdf/doi/10.1063/5.0003477/13952368/132409\_1\_online.p df}, 
        } 
        `,
        Citation: null
    },
    {
        Title: "Thermally driven two-magnet nano-oscillator with large spin-charge conversion",
        People: ["Bassim Arkook", "Christopher Safranski", "Rodolfo Rodriguez", "Ilya N. Krivorotov", "Tobias Schneider", "Kilian Lenz", "Jürgen Lindner", "Houchen Chang", "Mingzhong Wu", "Yaroslav Tserkovnyak", "Igor Barsukov"],
        Journal: "arXiv:1909.12445",
        DOI: "arxiv.org/abs/1909.12445",
        BibTex: `@misc{arkook2019thermally, 
        title={Thermally driven two-magnet nano-oscillator with large spin-charge conversion}, author={Bassim Arkook and Christopher Safranski and Rodolfo Rodriguez and Ilya N. Krivorotov and Tobias Schneider and Kilian Lenz and Jürgen Lindner and Houchen Chang and Mingzhong Wu and Yaroslav Tserkovnyak and Igor Barsukov}, 
        year={2019}, 
        eprint={1909.12445}, 
        archivePrefix={arXiv}, 
        primaryClass={cond-mat.mes-hall} 
        } 
        `,
        Citation: null
    },
    {
        Title: "Exploring magnetic resonance with a compass",
        People: ["Esther Cookson", "David Nelson", "Michael Anderson", "Daniel L. McKinney", "Igor Barsukov"],
        Journal: "Phys. Teach. 57, 633 (2019)",
        DOI: "doi.org/10.1119/1.5135797",
        BibTex: `@article{10.1119/1.5135797, 
        author = {Cookson, Esther and Nelson, David and Anderson, Michael and McKinney, Daniel L. and Barsukov, Igor}, 
        title = "{Exploring Magnetic Resonance with a Compass}", 
        journal = {The Physics Teacher}, 
        volume = {57}, 
        number = {9}, 
        pages = {633-635}, 
        year = {2019}, 
        month = {12},
        abstract = "{ Magnetic resonance is a quantum phenomenon and describes a resonant interaction of spins with electromagnetic fields. Its understanding requires advanced knowledge of quantum mechanics and condensed matter physics and thus often remains elusive to students. However, the great impact of this phenomenon on medicine, science, and technology makes magnetic resonance an important subject for general education, and it requires a graspable model for translating the physical concepts without resorting to advanced physics. One of the most common and familiar objects related to magnetism is the compass. Here, we develop an inexpensive tabletop demonstration experiment for magnetic resonance. The compass is placed into the magnetic field of a permanent magnet (strong refrigerator magnet); an alternating field of an electromagnetic coil (solenoid) excites a resonant oscillation of the compass needle. The experiment has been proven to catch the attention of audiences of all ages. }", issn = {0031-921X}, 
        doi = {10.1119/1.5135797}, 
        url = {https://doi.org/10.1119/1.5135797}, 
        eprint = {https://pubs.aip.org/aapt/pte/article-pdf/57/9/633/9871446/633\_1\_online.pdf},
        }
        `,
        Citation: null
    },
    {
        Title: "Giant nonlinear damping in nanoscale ferromagnets",
        People: ["I. Barsukov", "H.K. Lee", "A.A. Jara", "Y.-J. Chen", "A.M. Gonçalves", "C. Sha", "J.A. Katine", "R.E. Arias", "B.A. Ivanov", "I.N. Krivorotov"],
        Journal: "Sci. Adv. 5, eaav6943 (2019)",
        DOI: "dx.doi.org/10.1126/sciadv.aav6943",
        BibTex: `@article{ 
        doi:10.1126/sciadv.aav6943, 
        author = {I. Barsukov and H. K. Lee and A. A. Jara and Y.-J. Chen and A. M. Gonçalves and C. Sha and J. A. Katine and R. E. Arias and B. A. Ivanov and I. N. Krivorotov }, title = {Giant nonlinear damping in nanoscale ferromagnets}, 
        journal = {Science Advances}, 
        volume = {5}, 
        number = {10}, 
        pages = {eaav6943}, 
        year = {2019}, 
        doi = {10.1126/sciadv.aav6943}, 
        URL = {https://www.science.org/doi/abs/10.1126/sciadv.aav6943}, 
        eprint = {https://www.science.org/doi/pdf/10.1126/sciadv.aav6943}, 
        abstract = {Nonlinear magnon scattering redefines how nanomagnets respond to spin currents. Magnetic damping is a key metric for emerging technologies based on magnetic nanoparticles, such as spin torque memory and high-resolution biomagnetic imaging. Despite its importance, understanding of magnetic dissipation in nanoscale ferromagnets remains elusive, and the 
        damping is often treated as a phenomenological constant. Here, we report the discovery of a giant frequency-dependent nonlinear damping that strongly alters the response of a nanoscale ferromagnet to spin torque and microwave magnetic field. This damping mechanism originates from three-magnon scattering that is strongly enhanced by geometric confinement of magnons in the nanomagnet. We show that the giant nonlinear damping can invert the effect of spin torque on a nanomagnet, leading to an unexpected current-induced enhancement of damping by an antidamping torque. Our work advances the understanding of magnetic dynamics in nanoscale ferromagnets and spin torque devices.}}
        Control of spin-wave damping in YIG using spin currents from topological insulators @article{PhysRevApplied.11.034046, 
        title = {Control of Spin-Wave Damping in YIG Using Spin Currents from Topological Insulators}, author = {Navabi, Aryan and Liu, Yuxiang and Upadhyaya, Pramey and Murata, Koichi and Ebrahimi, Farbod and Yu, Guoqiang and Ma, Bo and Rao, Yiheng and Yazdani, Mohsen and Montazeri, Mohammad and Pan, Lei and Krivorotov, Ilya N. and Barsukov, Igor and Yang, Qinghui and Khalili Amiri, Pedram and Tserkovnyak, Yaroslav and Wang, Kang L.}, 
        journal = {Phys. Rev. Appl.}, 
        volume = {11}, 
        issue = {3}, 
        pages = {034046}, 
        numpages = {7}, 
        year = {2019}, 
        month = {Mar}, 
        publisher = {American Physical Society}, 
        doi = {10.1103/PhysRevApplied.11.034046}, 
        url = {https://link.aps.org/doi/10.1103/PhysRevApplied.11.034046} 
        } `,
        Citation: null
    },
    {
        Title: "Control of spin-wave damping in YIG using spin currents from topological insulators",
        People: ["A. Navabi", "Yuxiang Liu", "P. Upadhyaya", "K. Murata", "F. Ebrahimi", "Guoqiang Yu", "Bo Ma", "Rao Yiheng", "M. Yazdani", "M. Montazeri", "Lei Pan", "I. Krivorotov", "I. Barsukov", "Qinghui Yang", "P. Khalili Armiri", "Y. Tserkovnyak", "Kang L. Wang"],
        Journal: "Phys. Rev. Appl. 11, 034046 (2019)",
        DOI: "doi.org/10.1103/PhysRevApplied.11.034046",
        BibTex: null,
        Citation: null
    },
    {
        Title: "Oscillatory interlayer coupling in spin Hall systems",
        People: ["A. M. Gonçalves", "F. Garcia", "H. K. Lee", "A. Smith", "P. R. Soledade", "C. A. C. Passos", "M. Costa", "N. M. Souza-Neto", "I. N. Krivorotov", "L. C. Sampaio", "I. Barsukov"],
        Journal: "Sci. Rep. 8, 2318 (2018)",
        DOI: "doi.org/10.1038/s41598-018-20685-7",
        BibTex: null,
        Citation: null
    },
    {
        Title: "Spin Hall-induced auto-oscillations in ultrathin YIG grown on Pt",
        People: ["M. Evelt", "C. Safranski", "M. Aldosary", "V. E. Demidov", "I. Barsukov", "A. P. Nosov", "A. B. Rinkevich", "K. Sobotkiewich", "Xiaoqin Li", "Jing Shi", "I. N. Krivorotov", "S. O. Demokritov"],
        Journal: "Sci. Rep. 8, 1269 (2018)",
        DOI: "doi.org/10.1038/s41598-018-19606-5",
        BibTex: null,
        Citation: null
    },
    {
        Title: "Spin caloritronic nano-oscillator",
        People: ["Chris Safranski", "Igor Barsukov", "Han Kyu Lee", "Tobias Schneider", "Alejandro Jara", "Andrew Smith", "Houchen Chang", "Kilian Lenz", "Juergen Lindner", "Yaroslav Tserkovnyak", "Mingzhong Wu", "Ilya Krivorotov"],
        Journal: "Nat. Commun. 8, 117 (2017)",
        DOI: "doi.org/10.1038/s41467-017-00184-5",
        BibTex: null,
        Citation: null
    },
    {
        Title: "Parametric resonance of magnetization excited by electric field",
        People: ["Yu-Jin Chen", "Han Kyu Lee", "Roman Verba", "Jordan A. Katine", "Igor Barsukov", "Vasil Tiberkevich", "John Q. Xiao", "Andrei N. Slavin", "Ilya N. Krivorotov"],
        Journal: "Nano Lett. 17, 572 (2017)",
        DOI: "doi.org/10.1021/acs.nanolett.6b04725",
        BibTex: `@article{doi:10.1021/acs.nanolett.6b04725, 
        author = {Chen, Yu-Jin and Lee, Han Kyu and Verba, Roman and Katine, Jordan A. and Barsukov, Igor and Tiberkevich, Vasil and Xiao, John Q. and Slavin, Andrei N. and Krivorotov, Ilya N.}, 
        title = {Parametric Resonance of Magnetization Excited by Electric Field}, journal = {Nano Letters},
        volume = {17}, 
        number = {1}, 
        pages = {572-577}, 
        year = {2017}, 
        doi = {10.1021/acs.nanolett.6b04725}, 
        note ={PMID: 28002674}, 
        URL = { 
        https://doi.org/10.1021/acs.nanolett.6b04725 
        }, 
        eprint = { 
        https://doi.org/10.1021/acs.nanolett.6b04725 
        }}`,
        Citation: null
    },
    {
        Title: "Highly textured IrMn3(111) thin films grown by magnetron sputtering",
        People: ["A.A. Jara", "I. Barsukov", "B. Youngblood", "Y.-J. Chen", "J. Read", "Hua Chen", "P. Braganca", "I.N. Krivorotov"],
        Journal: "IEEE Magn. Lett. 7, 3104805 (2016)",
        DOI: "dx.doi.org/10.1109/LMAG.2016.2590464",
        BibTex: `@ARTICLE{7509605, 
        author={Jara, Alejandro A. and Barsukov, Igor and Youngblood, Brian and Chen, Yu-Jin and Read, John and Chen, Hua and Braganca, Patrick and Krivorotov, Ilya N.}, journal={IEEE Magnetics Letters}, 
        title={Highly Textured IrMn3(111) Thin Films Grown by Magnetron Sputtering}, year={2016}, 
        volume={7}, 
        number={}, 
        pages={1-5}, 
        keywords={X-ray scattering;Substrates;Perpendicular magnetic anisotropy;Magnetic domains;Lattices;Manganese;Spin electronics;anomalous Hall 
        effect;iridium-manganese;noncolinear antiferromagnets;textured thin films;crystallographic twinning}, 
        doi={10.1109/LMAG.2016.2590464}}`,
        Citation: null
    },
    {
        Title: "Magnetic anisotropy, damping, and interfacial spin transport in Pt/LSMO bilayers",
        People: ["Hankyu Lee", "I. Barsukov", "A. G. Swartz", "B. Kim", "Liu Yang", "H. Hwang", "I. N. Krivorotov"],
        Journal: "AIP Adv. 6, 055212 (2016)",
        DOI: "dx.doi.org/10.1063/1.4950971",
        BibTex: `@article{10.1063/1.4950971, 
        author = {Lee, H. K. and Barsukov, I. and Swartz, A. G. and Kim, B. and Yang, L. and Hwang, H. Y. and Krivorotov, I. N.}, 
        title = "{Magnetic anisotropy, damping, and interfacial spin transport in Pt/LSMO bilayers}", 
        journal = {AIP Advances}, 
        volume = {6}, 
        number = {5}, 
        pages = {055212}, 
        year = {2016}, 
        month = {05}, 
        abstract = "{ We report ferromagnetic resonance measurements of magnetic anisotropy and damping in epitaxial La0.7Sr0.3MnO3 (LSMO) and Pt capped LSMO thin films on SrTiO3 (001) substrates. The measurements reveal large negative perpendicular magnetic anisotropy and a weaker uniaxial in-plane anisotropy that are unaffected by the Pt cap. The Gilbert damping of the bare LSMO films is found to be low α = 1.9(1) × 10−3, and two-magnon scattering is determined to be significant and strongly anisotropic. The Pt cap increases the damping by 50\\% due to spin pumping, which is also directly detected via inverse spin Hall effect in Pt. Our work demonstrates efficient spin transport across the Pt/LSMO interface. }", 
        issn = {2158-3226}, 
        doi = {10.1063/1.4950971}, 
        url = {https://doi.org/10.1063/1.4950971}, 
        eprint = 
        {https://pubs.aip.org/aip/adv/article-pdf/doi/10.1063/1.4950971/12836890/055212\_1 \_online.pdf}, 
        }`,
        Citation: null
    },
    {
        Title: "Temperature dependence of perpendicular magnetic anisotropy in CoFeB thin films",
        People: ["Yu Fu", "I. Barsukov", "Jing Li", "A. M. Gonçalves", "C. C. Kuo", "M. Farle", "I. N. Krivorotov"],
        Journal: "Appl. Phys. Lett. 108, 142403 (2016)",
        DOI: "dx.doi.org/10.1063/1.4945682",
        BibTex: `@article{10.1063/1.4945682, 
        author = {Fu, Yu and Barsukov, I. and Li, Jing and Gonçalves, A. M. and Kuo, C. C. and Farle, M. and Krivorotov, I. N.}, 
        title = "{Temperature dependence of perpendicular magnetic anisotropy in CoFeB thin films}", 
        journal = {Applied Physics Letters}, 
        volume = {108}, 
        number = {14},
        pages = {142403}, 
        year = {2016}, 
        month = {04}, 
        abstract = "{We study perpendicular magnetic anisotropy in thin films of Ta/Co20Fe60B20/MgO by ferromagnetic resonance and find a linear temperature dependence for the first and second order uniaxial terms from 5 to 300 K. Our data suggest the possible hybridization of Fe-O orbitals at the CoFeB/MgO interface for the origin of the first order anisotropy. However, we also find that non-interfacial contributions to the anisotropy are present. An easy-cone anisotropy is found for the entire temperature range in the narrow region of film thicknesses around the spin reorientation transition 1.2–1.35 nm.}", 
        issn = {0003-6951}, 
        doi = {10.1063/1.4945682}, 
        url = {https://doi.org/10.1063/1.4945682}, 
        eprint = 
        {https://pubs.aip.org/aip/apl/article-pdf/doi/10.1063/1.4945682/14478287/142403\_1 \_online.pdf}, 
        }`,
        Citation: null
    },
    {
        Title: "Magnetic phase transitions in Ta/CoFeB/MgO multilayers",
        People: ["I. Barsukov", "Yu Fu", "C. Safranski", "Y.-J. Chen", "B. Youngblood", "A. M.Gonçalves", "M. Spasova", "M. Farle", "J. A. Katine", "C. C. Kuo", "I. N. Krivorotov"],
        Journal: "Appl. Phys. Lett. 106, 192407 (2015)",
        DOI: "dx.doi.org/10.1063/1.4921306",
        BibTex: `@article{10.1063/1.4921306, 
        author = {Barsukov, I. and Fu, Yu and Safranski, C. and Chen, Y.-J. and Youngblood, B. and Gonçalves, A. M. and Spasova, M. and Farle, M. and Katine, J. A. and Kuo, C. C. and Krivorotov, I. N.}, 
        title = "{Magnetic phase transitions in Ta/CoFeB/MgO multilayers}", journal = {Applied Physics Letters}, 
        volume = {106}, 
        number = {19}, 
        pages = {192407}, 
        year = {2015}, 
        month = {05}, 
        abstract = "{We study thin films and magnetic tunnel junction nanopillars based on Ta/Co20Fe60B20/MgO multilayers by electrical transport and magnetometry measurements. These measurements suggest that an ultrathin magnetic oxide layer forms at the Co20Fe60B20/MgO interface. At approximately 160 K, the oxide undergoes a phase transition from an insulating antiferromagnet at low temperatures to a conductive weak ferromagnet at high temperatures. This interfacial magnetic oxide is expected to have significant impact on the magnetic properties of CoFeB-based multilayers used in spin torque memories.}",
        issn = {0003-6951}, 
        doi = {10.1063/1.4921306}, 
        url = {https://doi.org/10.1063/1.4921306}, 
        eprint = 
        {https://pubs.aip.org/aip/apl/article-pdf/doi/10.1063/1.4921306/14314381/192407\_1 \_online.pdf}, 
        }`,
        Citation: null
    },
    {
        Title: "Field-dependent perpendicular magnetic anisotropy in CoFeB thin films",
        People: ["I. Barsukov", "Yu Fu", "A. M. Gonçalves", "M. Spasova", "M. Farle", "L. C. Sampaio", "R. E. Arias", "I. N. Krivorotov"],
        Journal: "Appl. Phys. Lett. 105, 152403 (2014)",
        DOI: "dx.doi.org/10.1063/1.4897939",
        BibTex: `@article{10.1063/1.4897939, 
        author = {Barsukov, I. and Fu, Yu and Gonçalves, A. M. and Spasova, M. and Farle, M. and Sampaio, L. C. and Arias, R. E. and Krivorotov, I. N.}, 
        title = "{Field-dependent perpendicular magnetic anisotropy in CoFeB thin films}", journal = {Applied Physics Letters}, 
        volume = {105}, 
        number = {15}, 
        pages = {152403}, 
        year = {2014}, 
        month = {10}, 
        abstract = "{We report ferromagnetic resonance measurements of perpendicular magnetic anisotropy in thin films of Ta/Co20Fe60B20/MgO as a function of the Co20Fe60B20 layer thickness. The first and second order anisotropy terms show unexpectedly strong dependence on the external magnetic field applied to the system during the measurements. We propose strong interfacial spin pinning as a possible origin of the field-dependent anisotropy. Our results imply that high-field anisotropy measurements cannot be directly used for quantitative evaluation of zero-field performance parameters of CoFeB-based devices such as spin torque memory.}", issn = {0003-6951}, 
        doi = {10.1063/1.4897939}, 
        url = {https://doi.org/10.1063/1.4897939}, 
        eprint = 
        {https://pubs.aip.org/aip/apl/article-pdf/doi/10.1063/1.4897939/14093993/152403\_1 \_online.pdf}, 
        }
        `,
        Citation: null
    },
    {
        Title: "Mechanism of tailored magnetic anisotropy in amorphous Co68Fe24Zr8 thin films",
        People: ["Yu Fu", "I. Barsukov", "R. Meckenstock", "J. Lindner", "H. Raanaei", "B. Hjörvarsson", "M. Farle"],
        Journal: "Appl. Phys. Lett. 104, 072409 (2014)",
        DOI: "dx.doi.org/10.1063/1.4865369",
        BibTex: `@article{10.1063/1.4865369, 
        author = {Fu, Yu and Barsukov, I. and Meckenstock, R. and Lindner, J. and Raanaei, H. and Hjörvarsson, B. and Farle, M.},
        title = "{Mechanism of tailored magnetic anisotropy in amorphous Co68Fe24Zr8 thin films}", 
        journal = {Applied Physics Letters}, 
        volume = {104}, 
        number = {7}, 
        pages = {072409}, 
        year = {2014}, 
        month = {02}, 
        abstract = "{The mechanism of tailored magnetic anisotropy in amorphous Co68Fe24Zr8 thin films was investigated by ferromagnetic resonance (FMR) on samples deposited without an applied magnetic field, with an out-of-plane field and an in-plane field. Analysis of FMR spectra profiles, high frequency susceptibility calculations, and statistical simulations using a distribution of local uniaxial magnetic anisotropy reveal the presence of atomic configurations with local uniaxial anisotropy, of which the direction can be tailored while the magnitude remains at an intrinsically constant value of 3.0(2) kJ/m3. The in-plane growth field remarkably sharpens the anisotropy distribution and increases the sample homogeneity. The results benefit designing multilayer spintronic devices based on highly homogeneous amorphous layers with tailored magnetic anisotropy.}", 
        issn = {0003-6951}, 
        doi = {10.1063/1.4865369}, 
        url = {https://doi.org/10.1063/1.4865369}, 
        eprint = 
        {https://pubs.aip.org/aip/apl/article-pdf/doi/10.1063/1.4865369/13682447/072409\_1 \_online.pdf}, 
        }
        `,
        Citation: null
    },
    {
        Title: "Uniaxial Anisotropy and its Manipulation in Amorphous Co68Fe24Zr8 Thin Films (invited)",
        People: ["Yu Fu", "I. Barsukov", "R. Meckenstock", "J. Lindner", "Y. Zhai", "B. Hjörvarsson", "M. Farle"],
        Journal: "J. Appl. Phys. 115, 172605 (2014)",
        DOI: "dx.doi.org/10.1063/1.4870591",
        BibTex: `@article{10.1063/1.4870591, 
        author = {Fu, Yu and Barsukov, I. and Meckenstock, R. and Lindner, J. and Zhai, Y. and Hjörvarsson, B. and Farle, M.}, 
        title = "{Uniaxial anisotropy and its manipulation in amorphous Co68Fe24Zr8 thin films (invited)}", 
        journal = {Journal of Applied Physics}, 
        volume = {115}, 
        number = {17}, 
        pages = {172605}, 
        year = {2014},
        month = {04}, 
        abstract = "{We have proven that the growth of Co68Fe24Zr8 layers under external field yields a uniaxial anisotropy, defined by the direction of the field. No magnetic coupling is present between Co68Fe24Zr8 layers when separated by a 3 nm of Al70Zr30. The anisotropy axis can therefore be manipulated at will and the direction can be tailored, layer by layer in multilayers, by the choice of the direction of the applied field during growth. The g-factor (2.13) and the anisotropy constant, obtained from ferromagnetic resonance, support the existence of short-range order. The relation between the temperature dependences of magnetic anisotropy and magnetization are partially captured by Callen-Callen power law.}", 
        issn = {0021-8979}, 
        doi = {10.1063/1.4870591}, 
        url = {https://doi.org/10.1063/1.4870591}, 
        eprint = 
        {https://pubs.aip.org/aip/jap/article-pdf/doi/10.1063/1.4870591/13975888/172605\_1 \_online.pdf}, 
        }
        `,
        Citation: null
    },
    {
        Title: "Spin torque ferromagnetic resonance with magnetic field modulation",
        People: ["A. M. Gonçalves", "I. Barsukov", "Y.-J. Chen", "L. Yang", "J. A. Katine", "I. N. Krivorotov"],
        Journal: "Appl. Phys. Lett. 103, 172406 (2013)",
        DOI: "doi.org/10.1063/1.4826927",
        BibTex: `@article{10.1063/1.4826927, 
        author = {Gonçalves, A. M. and Barsukov, I. and Chen, Y.-J. and Yang, L. and Katine, J. A. and Krivorotov, I. N.}, 
        title = "{Spin torque ferromagnetic resonance with magnetic field modulation}", journal = {Applied Physics Letters}, 
        volume = {103}, 
        number = {17}, 
        pages = {172406}, 
        year = {2013}, 
        month = {10}, 
        abstract = "{We demonstrate a technique of broadband spin torque ferromagnetic resonance (ST-FMR) with magnetic field modulation for measurements of spin wave properties in magnetic nanostructures. This technique gives great improvement in sensitivity over the conventional ST-FMR measurements, and application of this technique to nanoscale magnetic tunnel junctions (MTJs) reveals a rich spectrum of standing spin wave eigenmodes. Comparison of the ST-FMR measurements with micromagnetic simulations of the spin wave spectrum allows us to explain the character of low-frequency magnetic excitations in nanoscale MTJs.}", issn = {0003-6951},
        doi = {10.1063/1.4826927}, 
        url = {https://doi.org/10.1063/1.4826927}, 
        eprint = 
        {https://pubs.aip.org/aip/apl/article-pdf/doi/10.1063/1.4826927/14282836/172406\_1 \_online.pdf}, 
        } 
        `,
        Citation: null
    },
    {
        Title: "Observation of Current-driven Oscillatory Domain Wall Motion in Ni80Fe20/Co Bilayer Nanowire",
        People: ["W. Zhang", "P. K. J. Wong", "P. Yan", "J. Wu", "S. A. Morton", "X. R. Wang", "X. F. Hu", "Y. B. Xu", "A. Scholl", "A. Young", "I. Barsukov", "M. Farle", "G. van der Laan"],
        Journal: "Appl. Phys. Lett. 103, 042403 (2013)",
        DOI: "doi.org/10.1063/1.4816359",
        BibTex: `@article{10.1063/1.4816359, 
        author = {Zhang, W. and Wong, P. K. J. and Yan, P. and Wu, J. and Morton, S. A. and Wang, X. R. and Hu, X. F. and Xu, Y. B. and Scholl, A. and Young, A. and Barsukov, I. and Farle, M. and van der Laan, G.}, 
        title = "{Observation of current-driven oscillatory domain wall motion in Ni80Fe20/Co bilayer nanowire}", 
        journal = {Applied Physics Letters}, 
        volume = {103}, 
        number = {4}, 
        pages = {042403}, 
        year = {2013}, 
        month = {07}, 
        abstract = "{Direct observation of current-driven oscillatory domain wall motion above the Walker breakdown by x-ray magnetic circular dichroism in photoemission electron microscopy is reported in Ni80Fe20/Co nanowire, showing micrometer-scale displacement at ∼13 MHz. We identify two key factors that enhance the oscillatory motion: (i) increase of the hard-axis magnetic anisotropy field value |H⊥| and (ii) increase of the ratio between non-adiabatic spin-transfer parameter to the Gilbert damping coefficient, β/α, which is required to be larger than 1. These findings point to an important route to tune the long-scale oscillatory domain wall motion using appropriate geometry and materials.}", 
        issn = {0003-6951}, 
        doi = {10.1063/1.4816359}, 
        url = {https://doi.org/10.1063/1.4816359}, 
        eprint = 
        {https://pubs.aip.org/aip/apl/article-pdf/doi/10.1063/1.4816359/14287723/042403\_1 \_online.pdf}, 
        }
        `,
        Citation: null
    },
    {
        Title: "Surface morphology and atomic structure of thin layers of Fe3Si on GaAs(001) and their magnetic properties",
        People: ["S. Noor", "I. Barsukov", "M. S. Özkan", "L. Elbers", "N. Melnichak", "J. Lindner", "M. Farle", "U. Köhler"],
        Journal: "J. Appl. Phys. 113, 103908 (2013)",
        DOI: "doi.org/10.1063/1.4795163",
        BibTex: `@article{10.1063/1.4795163, 
        author = {Noor, S. and Barsukov, I. and Özkan, M. S. and Elbers, L. and Melnichak, N. and Lindner, J. and Farle, M. and Köhler, U.}, 
        title = "{Surface morphology and atomic structure of thin layers of Fe3Si on GaAs(001) and their magnetic properties}", 
        journal = {Journal of Applied Physics}, 
        volume = {113}, 
        number = {10}, 
        pages = {103908}, 
        year = {2013}, 
        month = {03}, 
        abstract = "{The structural and magnetic properties of ultrathin near-stoichiometric Fe3Si layers on GaAs(001) are investigated after using scanning tunneling microscopy (STM) analysis to optimize the deposition process. This includes atomic resolution imaging of the surface as measured by STM revealing the atomic ordering and characteristic defects in the topmost layers. Emphasis is laid on connections between the layer morphology and its magnetic properties, which are analysed by in situ MOKE, FMR, and SQUID magnetometry. Upon nucleation, the Fe3Si islands behave like superparamagnetic nanoparticles where we find a quantitative agreement between the size of the nanoparticles and their superspin. At higher coverage, the Fe3Si layers show ferromagnetic behaviour. Here, we investigate the superposition of the magnetocrystalline and the uniaxial anisotropies where the latter can be excluded to be caused by shape anisotropy. Furthermore, an unexpected increase of the magnetic moment towards low coverage can be observed which apart from an increased orbital moment can be attributed to an increased step density.}", 
        issn = {0021-8979}, 
        doi = {10.1063/1.4795163}, 
        url = {https://doi.org/10.1063/1.4795163}, 
        eprint = 
        {https://pubs.aip.org/aip/jap/article-pdf/doi/10.1063/1.4795163/15108689/103908\_1 \_online.pdf}, 
        } 
        `,
        Citation: null
    },
    {
        Title: "Tuning magnetic relaxation by oblique deposition",
        People: ["I. Barsukov", "P. Landeros", "R. Meckenstock", "J. Lindner", "D. Spoddig", "Zi-An Li", "B. Krumme", "H. Wende", "D.L. Mills", "M. Farle"],
        Journal: "Phys. Rev. B 85, 014420 (2012)",
        DOI: "doi.org/10.1103/PhysRevB.85.014420",
        BibTex: `@article{PhysRevB.85.014420, 
        title = {Tuning magnetic relaxation by oblique deposition},
        author = {Barsukov, I. and Landeros, P. and Meckenstock, R. and Lindner, J. and Spoddig, D. and Li, Zi-An and Krumme, B. and Wende, H. and Mills, D. L. and Farle, M.}, journal = {Phys. Rev. B}, 
        volume = {85}, 
        issue = {1}, 
        pages = {014420}, 
        numpages = {6}, 
        year = {2012}, 
        month = {Jan}, 
        publisher = {American Physical Society}, 
        doi = {10.1103/PhysRevB.85.014420}, 
        url = {https://link.aps.org/doi/10.1103/PhysRevB.85.014420} 
        } 
        `,
        Citation: null
    },
    {
        Title: "Magnetocrystalline anisotropy and Gilbert damping in iron-rich Fe-Si thin films",
        People: ["I. Barsukov", "S.Mankovsky", "A. Rubacheva", "R. Meckenstock", "D. Spoddig", "J. Lindner", "N. Melnichak", "B. Krumme", "S. I. Makarov", "H. Wende", "H. Ebert", "M. Farle"],
        Journal: "Phys. Rev. B 84, 180405(R) (2011)",
        DOI: "doi.org/10.1103/PhysRevB.84.180405",
        BibTex: "@article{PhysRevB.84.180405, \ntitle = {Magnetocrystalline anisotropy and Gilbert damping in iron-rich Fe${}_{1\\ensuremath{-}x}$Si${}_{x}$ thin films}, \nauthor = {Barsukov, I. and Mankovsky, S. and Rubacheva, A. and Meckenstock, R. and Spoddig, D. and Lindner, J. and Melnichak, N. and Krumme, B. and Makarov, S. I. and Wende, H. and Ebert, H. and Farle, M.}, \njournal = {Phys. Rev. B}, \nvolume = {84}, \nissue = {18}, \npages = {180405}, \nnumpages = {4}, \nyear = {2011}, \nmonth = {Nov}, \npublisher = {American Physical Society}, \ndoi = {10.1103/PhysRevB.84.180405}, \nurl = {https://link.aps.org/doi/10.1103/PhysRevB.84.180405} \n}",
        Citation: null
    },
    {
        Title: "Frequency dependence of spin relaxation in periodic systems",
        People: ["I. Barsukov", "F. M. Römer", "R. Meckenstock", "K. Lenz", "J. Lindner", "S. Hemken to Krax", "A. Banholzer", "M. Körner", "J. Grebing", "J. Fassbender", "M. Farle"],
        Journal: "Phys. Rev. B 84, 140410(R) (2011)",
        DOI: "doi.org/10.1103/PhysRevB.84.140410",
        BibTex: `@article{PhysRevB.84.140410, 
        title = {Frequency dependence of spin relaxation in periodic systems}, author = {Barsukov, I. and R\"omer, F. M. and Meckenstock, R. and Lenz, K. and Lindner, J. and Hemken to Krax, S. and Banholzer, A. and K\"orner, M. and Grebing, J. and Fassbender, J. and Farle, M.},
        journal = {Phys. Rev. B}, 
        volume = {84}, 
        issue = {14}, 
        pages = {140410}, 
        numpages = {4}, 
        year = {2011}, 
        month = {Oct}, 
        publisher = {American Physical Society}, 
        doi = {10.1103/PhysRevB.84.140410}, 
        url = {https://link.aps.org/doi/10.1103/PhysRevB.84.140410} 
        } 
        `,
        Citation: null
    },
    {
        Title: "Tailored Magnetic Anisotropy in an Amorphous Trilayer",
        People: ["Y. Fu", "I. Barsukov", "H. Raanaei", "M. Spasova", "J. Lindner", "R. Meckenstock", "M. Farle", "B. Hjörvarsson"],
        Journal: "J. Appl. Phys. 109, 113908 (2011)",
        DOI: "doi.org/10.1063/1.3587189",
        BibTex: `@article{10.1063/1.3587189, 
        author = {Fu, Yu and Barsukov, I. and Raanaei, H. and Spasova, M. and Lindner, J. and Meckenstock, R. and Farle, M. and Hjörvarsson, B.}, 
        title = "{Tailored magnetic anisotropy in an amorphous trilayer}", 
        journal = {Journal of Applied Physics}, 
        volume = {109}, 
        number = {11}, 
        pages = {113908}, 
        year = {2011}, 
        month = {06}, 
        abstract = "{An amorphous Co68Fe24Zr8(3 nm)/Al70Zr30(3 nm)/Co68Fe24Zr8(3 nm) trilayer system has been investigated using in-plane and out-of-plane angular dependent ferromagnetic resonance at different frequencies. The in-plane magnetic anisotropy is uniaxial, retaining its value of (2.9 ± 0.1) × 103 J/m3 for each magnetic layer, whereas its direction was tailored independently in an arbitrary manner by applying an external magnetic field during the film deposition. The perpendicular anisotropy constant, supposed to reflect the interface quality, is nearly identical for both layers. Furthermore, the magnetic layers act independently upon each other due to the absence of interlayer coupling.}", 
        issn = {0021-8979}, 
        doi = {10.1063/1.3587189}, 
        url = {https://doi.org/10.1063/1.3587189}, 
        eprint = 
        {https://pubs.aip.org/aip/jap/article-pdf/doi/10.1063/1.3587189/15081357/113908\_1 \_online.pdf}, 
        }
        `,
        Citation: null
    },
    {
        Title: "Magnetism of Single-Crystalline Fe Nanostructures",
        People: ["J. Lindner", "C. Hassel", "A. V. Trunova", "F. M. Römer", "S. Stienen", "I. Barsukov"],
        Journal: "J. Nanosci. Nanotechnol. 10, 6161 (2010)",
        DOI: "doi.org/10.1166/jnn.2010.2597",
        BibTex: null,
        Citation: null
    },
    {
        Title: "Tailoring Spin Relaxation in Thin Films by Tuning Extrinsic Relaxation Channels",
        People: ["I. Barsukov", "R. Meckenstock", "J. Lindner", "M. Möller", "C. Hassel", "O. Posth", "M. Farle"],
        Journal: "IEEE Trans. Magn. 46, 2252 (2010)",
        DOI: "doi.org/10.1109/TMAG.2010.2044482",
        BibTex: `@ARTICLE{5467613, 
        author={Barsukov, Igor and Meckenstock, Ralf and Lindner, Jürgen and Moller, Marc and Hassel, Christoph and Posth, Oliver and Farle, Michael and Wende, Heiko}, 
        journal={IEEE Transactions on Magnetics}, 
        title={Tailoring Spin Relaxation in Thin Films by Tuning Extrinsic Relaxation Channels}, year={2010}, 
        volume={46}, 
        number={6}, 
        pages={2252-2255}, 
        keywords={Transistors;Damping;Magnetic resonance;Scattering;Magnetization;Frequency dependence;Anisotropic magnetoresistance;Iron;Torque;Magnetic anisotropy;Magnetic resonance;relaxation processes;thin films}, 
        doi={10.1109/TMAG.2010.2044482}} 
        `,
        Citation: null
    },
    {
        Title: "Magnetocrystalline anisotropy of Fe-Si alloys on MgO(001)",
        People: ["Y. N. Zhang", "J. X. Cao", "I. Barsukov", "J. Lindner", "B. Krumme", "H. Wende", "R. Q. Wu"],
        Journal: "Phys. Rev. B 81, 144418 (2010)",
        DOI: "doi.org/10.1103/PhysRevB.81.144418",
        BibTex: `@article{PhysRevB.81.144418, 
        title = {Magnetocrystalline anisotropy of Fe-Si alloys on MgO(001)}, 
        author = {Zhang, Y. N. and Cao, J. X. and Barsukov, I. and Lindner, J. and Krumme, B. and Wende, H. and Wu, R. Q.}, 
        journal = {Phys. Rev. B}, 
        volume = {81}, 
        issue = {14}, 
        pages = {144418}, 
        numpages = {6}, 
        year = {2010}, 
        month = {Apr}, 
        publisher = {American Physical Society}, 
        doi = {10.1103/PhysRevB.81.144418}, 
        url = {https://link.aps.org/doi/10.1103/PhysRevB.81.144418} 
        } 
        `,
        Citation: null
    },
    {
        Title: "Two-magnon damping in thin films in case of canted magnetization: Theory versus experiment",
        People: ["J. Lindner", "I. Barsukov", "C. Raeder", "C. Hassel", "O. Posth", "R. Meckenstock", "P. Landeros", "D.L. Mills"],
        Journal: "Phys. Rev. B 80, 224421 (2009)",
        DOI: "doi.org/10.1103/PhysRevB.80.224421",
        BibTex: `@article{PhysRevB.80.224421, 
        title = {Two-magnon damping in thin films in case of canted magnetization: Theory versus experiment}, 
        author = {Lindner, J. and Barsukov, I. and Raeder, C. and Hassel, C. and Posth, O. and Meckenstock, R. and Landeros, P. and Mills, D. L.}, 
        journal = {Phys. Rev. B}, 
        volume = {80},
        issue = {22}, 
        pages = {224421}, 
        numpages = {7}, 
        year = {2009}, 
        month = {Dec}, 
        publisher = {American Physical Society}, 
        doi = {10.1103/PhysRevB.80.224421}, 
        url = {https://link.aps.org/doi/10.1103/PhysRevB.80.224421} 
        } 
        `,
        Citation: null
    },
    {
        Title: "Erratum: Spin dynamics in ferromagnets: Gilbert damping and two-magnon scattering [Phys. Rev. B 76, 104416 (2007)]",
        People: ["Kh. Zakeri", "J. Lindner", "I. Barsukov", "R. Meckenstock", "M. Farle", "U. von Hörsten", "H. Wende", "W. Keune", "J. Rocker", "S. S. Kalarickal", "K. Lenz", "W. Kuch", "K. Baberschke", "Z. Frait"],
        Journal: "Phys. Rev. B 80, 059901(E) (2009)",
        DOI: "doi.org/10.1103/PhysRevB.80.059901",
        BibTex: `@article{PhysRevB.80.059901, 
        title = {Erratum: Spin dynamics in ferromagnets: Gilbert damping and two-magnon scattering [Phys. Rev. B 76, 104416 (2007)]}, 
        author = {Zakeri, Kh. and Lindner, J. and Barsukov, I. and Meckenstock, R. and Farle, M. and von H\"orsten, U. and Wende, H. and Keune, W. and Rocker, J. and Kalarickal, S. S. and Lenz, K. and Kuch, W. and Baberschke, K. and Frait, Z.}, 
        journal = {Phys. Rev. B}, 
        volume = {80}, 
        issue = {5}, 
        pages = {059901}, 
        numpages = {3}, 
        year = {2009}, 
        month = {Aug}, 
        publisher = {American Physical Society}, 
        doi = {10.1103/PhysRevB.80.059901}, 
        url = {https://link.aps.org/doi/10.1103/PhysRevB.80.059901} 
        } 
        `,
        Citation: null
    },
    {
        Title: "Fe monolayers on InAs(001): An in situ study of surface, interface and volume magnetic anisotropy",
        People: ["F. M. Römer", "C. Hassel", "Kh. Zakeri", "C. Tomaz", "I. Barsukov", "R. Meckenstock", "J. Lindner", "M. Farle"],
        Journal: "J. Magn. Magn. Mat. 321, 2232-2238 (2009)",
        DOI: "doi.org/10.1016/j.jmmm.2009.01.047",
        BibTex: `@article{ROMER20092232, 
        title = {Fe monolayers on InAs(001): An in situ study of surface, interface and volume magnetic anisotropy}, 
        journal = {Journal of Magnetism and Magnetic Materials}, 
        volume = {321}, 
        number = {14}, 
        pages = {2232-2238}, 
        year = {2009}, 
        note = {Current Perspectives: Modern Microwave Materials}, 
        issn = {0304-8853}, 
        doi = {https://doi.org/10.1016/j.jmmm.2009.01.047}, 
        url = {https://www.sciencedirect.com/science/article/pii/S0304885309000377},
        author = {F.M. Römer and C. Hassel and Kh. Zakeri and C. Tomaz and I. Barsukov and R. Meckenstock and J. Lindner and M. Farle}, 
        keywords = {Magnetic anisotropy, Magnetic thin film, Ferromagnetic resonance}, abstract = {The magnetic anisotropy of epitaxial Fe films with thicknesses in the range of 2–142 monolayers (ML) grown on {4×2} reconstructed InAs(001) was investigated by in situ ferromagnetic resonance. The easy magnetization direction was found to be parallel to the [11¯0]-direction for Fe films below 4ML, while it rotates by 45∘ toward the [100]-direction. It is observed that both surface-interface and volume contribution to the perpendicular anisotropy favor an easy axis perpendicular to the film plane. The cubic surface-interface anisotropy is relatively large with easy axes along 〈11¯0〉-directions in contrast to the volume contribution which favors easy axes along the 〈110〉-directions. The volume contribution is found to be larger than the Fe bulk cubic anisotropy. A thickness independent uniaxial anisotropy has been found in films with a thickness of 2 up to 142ML.} 
        } 
        `,
        Citation: null
    },
    {
        Title: "Magnetic Characterisation of Iron Nanocubes",
        People: ["A. V. Trunova", "R. Meckenstock", "I. Barsukov", "Ch. Hassel", "O. Margeat", "M. Spasova", "J. Lindner", "M. Farle"],
        Journal: "J. Appl. Phys. 104, 093904 (2008)",
        DOI: "doi.org/10.1063/1.3005985",
        BibTex: `@article{10.1063/1.3005985, 
        author = {Trunova, Anastasia V. and Meckenstock, R. and Barsukov, I. and Hassel, C. and Margeat, O. and Spasova, M. and Lindner, J. and Farle, M.}, 
        title = "{Magnetic characterization of iron nanocubes}", 
        journal = {Journal of Applied Physics}, 
        volume = {104}, 
        number = {9}, 
        pages = {093904}, 
        year = {2008}, 
        month = {11}, 
        abstract = "{Nearly perfect single crystalline Fe core-shell nanocubes with (100) facets and 13.6 nm edge length were prepared by wet-chemical methods. While the core is metallic, the shell is composed of either Fe3O4 or γ-Fe2O3. The cubes were deposited onto GaAs substrates with monolayer coverage as proved by scanning electron microscopy. Oxygen and hydrogen plasmas were used to remove the ligand system and the oxide shell. Both types of samples were investigated by ferromagnetic resonance. While the g-factor (g=2.09) and crystalline anisotropy (K4=4.8×104 J/m3) of the pure iron cubes show up with bulk values, the saturation magnetization is reduced to (M(5K)=(1.2±0.12)×106 A/m) 70\\% of bulk value and the effective damping parameter (α=0.03) is increased by one order of magnitude with respect to bulk Fe.}", issn = {0021-8979}, 
        doi = {10.1063/1.3005985}, 
        url = {https://doi.org/10.1063/1.3005985}, 
        eprint = 
        {https://pubs.aip.org/aip/jap/article-pdf/doi/10.1063/1.3005985/6599647/093904\_1\_online.pd f}, 
        }
        `,
        Citation: null
    },
    {
        Title: "Pt-Catalyzed Growth of Ni Nanoparticles in Aqueous CTAB Solution",
        People: ["Marek Grzelczak", "Jorge Pérez-Juste", "Benito Rodríguez-González", "Marina Spasova", "Igor Barsukov", "Michael Farle", "Luis M. Liz-Marzán"],
        Journal: "Chem. Mater. 20 (16), 5399 (2008)",
        DOI: "doi.org/10.1021/cm800665s",
        BibTex: `@article{doi:10.1021/cm800665s, 
        author = {Grzelczak, Marek and Pérez-Juste, Jorge and Rodríguez-González, Benito and Spasova, Marina and Barsukov, Igor and Farle, Michael and Liz-Marzán, Luis M.}, 
        title = {Pt-Catalyzed Growth of Ni Nanoparticles in Aqueous CTAB Solution}, journal = {Chemistry of Materials}, 
        volume = {20}, 
        number = {16}, 
        pages = {5399-5405}, 
        year = {2008}, 
        doi = {10.1021/cm800665s}, 
        URL = { 
        https://doi.org/10.1021/cm800665s 
        }, 
        eprint = { 
        https://doi.org/10.1021/cm800665s 
        } 
        } 
        `,
        Citation: null
    },
    {
        Title: "Spin and orbital magnetism in ordered Fe3±δSi1±δ binary Heusler structures: Theory versus Experiment",
        People: ["Kh. Zakeri", "S.J. Hashemifar", "J. Lindner", "I. Barsukov", "R. Meckenstock", "P. Kratzer", "Z. Frait", "M. Farle"],
        Journal: "Phys. Rev. B 77, 104430 (2008)",
        DOI: "doi.org/10.1103/PhysRevB.77.104430",
        BibTeX: "@article{PhysRevB.77.104430, \n  title = {Spin and orbital magnetism in ordered ${\\mathrm{Fe}}_{3\\ifmmode\\pm\\else\\textpm\\fi{}\\ensuremath{\\delta}}{\\mathrm{Si}}_{1\\ensuremath {\\mp}\\ensuremath{\\delta}}$ binary Heusler structures: Theory versus experiment}, \n  author = {Zakeri, Khalil and Hashemifar, S. Javad and Lindner, J\\\"urgen and Barsukov, Igor and Meckenstock, Ralf and Kratzer, Peter and Frait, Zden\\ifmmode \\check{e}\\else \\v{e}\\fi{}k and Farle, Michael}, \n  journal = {Phys. Rev. B}, \n  volume = {77}, \n  issue = {10}, \n  pages = {104430}, \n  numpages = {5}, \n  year = {2008}, \n  month = {Mar}, \n  publisher = {American Physical Society}, \n  doi = {10.1103/PhysRevB.77.104430}, \n  url = {https://link.aps.org/doi/10.1103/PhysRevB.77.104430} \n}",
        Citation: null
    },
    {
        Title: "Magnetic properties of epitaxial Fe3Si/MgO(001) thin films",
        People: ["Kh. Zakeri", "I. Barsukov", "N. K. Utochkina", "F. M. Römer", "J. Lindner", "R. Meckenstock", "U. von Hörsten", "H. Wende", "W. Keune", "M. Farle", "S. S. Kalarickal", "K. Lenz", "Z. Frait"],
        Journal: "Phys. Rev. B 76, 214421 (2007)",
        DOI: "doi.org/10.1103/PhysRevB.76.214421",
        BibTex: "@article{PhysRevB.76.214421, \ntitle = {Magnetic properties of epitaxial ${\\mathrm{Fe}}_{3}\\mathrm{Si}\\u2215\\mathrm{Mg}\\mathrm{O}(001) thin films}, \nauthor = {Zakeri, Kh. and Barsukov, I. and Utochkina, N. K. and R\\\"omer, F. M. and Lindner, J. and Meckenstock, R. and von H\\\"orsten, U. and Wende, H. and Keune, W. and Farle, M. and Kalarickal, S. S. and Lenz, K. and Frait, Z.}, \njournal = {Phys. Rev. B}, \nvolume = {76}, \nissue = {21}, \npages = {214421}, \nnumpages = {9}, \nyear = {2007}, \nmonth = {Dec}, \npublisher = {American Physical Society}, \ndoi = {10.1103/PhysRevB.76.214421}, \nurl = {https://link.aps.org/doi/10.1103/PhysRevB.76.214421} \n}",
        Citation: null
    },
    {
        Title: "Locally Resolved Ferromagnetic Resonance in Co Stripes",
        People: ["R. Meckenstock", "I. Barsukov", "O. Posth", "J. Lindner", "A. Butko", "D. Spoddig"],
        Journal: "Appl. Phys. Lett. 91, 142507 (2007)",
        DOI: "doi.org/10.1063/1.2794026",
        BibTex: `@article{10.1063/1.2794026, 
        author = {Meckenstock, Ralf and Barsukov, I. and Posth, O. and Lindner, J. and Butko, A. and Spoddig, D.}, 
        title = "{Locally resolved ferromagnetic resonance in Co stripes}", 
        journal = {Applied Physics Letters}, 
        volume = {91}, 
        number = {14}, 
        pages = {142507}, 
        year = {2007}, 
        month = {10}, 
        abstract = "{Microwave excitations of Co stripes of 100×1.5×0.025μm3 were investigated by angular dependent ferromagnetic resonance (FMR) and by locally resolved scanning thermal microscopy based (SThM) FMR, offering a lateral resolution of \\&lt;100nm and a sensitivity of 106 spins. Besides the uniform excitation, backward volume modes and a rim resonance were identified by SThM-FMR imaging. Micromagnetic simulations (OOMMF) confirm the experimentally observed lateral confinement of these modes. The magnetic parameters of the Co stripes correspond to the ones of Co bulk with a surface anisotropy Ks=0.5mJ∕m2.}", issn = {0003-6951}, 
        doi = {10.1063/1.2794026}, 
        url = {https://doi.org/10.1063/1.2794026},
        eprint = 
        {https://pubs.aip.org/aip/apl/article-pdf/doi/10.1063/1.2794026/13230368/142507\_1\_online.p df}, 
        } 
        `,
        Citation: null
    },
    {
        Title: "Spin dynamics in ferromagnets: Gilbert damping and two-magnon scattering",
        People: ["Kh. Zakeri", "J. Lindner", "I. Barsukov", "R. Meckenstock", "M. Farle", "U. von Hörsten", "H. Wende", "W. Keune", "J. Rocker", "S. S. Kalarickal", "K. Lenz", "W. Kuch", "K. Baberschke", "Z. Frait"],
        Journal: "Phys. Rev. B 76, 104416 (2007)",
        DOI: "doi.org/10.1103/PhysRevB.76.104416",
        BibTex: `@article{PhysRevB.76.104416, 
        title = {Spin dynamics in ferromagnets: Gilbert damping and two-magnon scattering}, author = {Zakeri, Kh. and Lindner, J. and Barsukov, I. and Meckenstock, R. and Farle, M. and von H\"orsten, U. and Wende, H. and Keune, W. and Rocker, J. and Kalarickal, S. S. and Lenz, K. and Kuch, W. and Baberschke, K. and Frait, Z.}, 
        journal = {Phys. Rev. B}, 
        volume = {76}, 
        issue = {10}, 
        pages = {104416}, 
        numpages = {8}, 
        year = {2007}, 
        month = {Sep}, 
        publisher = {American Physical Society}, 
        doi = {10.1103/PhysRevB.76.104416}, 
        url = {https://link.aps.org/doi/10.1103/PhysRevB.76.104416} 
        } 
        `,
        Citation: null
    },
    {
        Title: "Low relaxation rate in epitaxial vanadium-doped iron ultrathin films",
        People: ["C. Scheck", "L. Cheng", "I. Barsukov", "Z. Frait", "W.E. Bailey"],
        Journal: "Phys. Rev. Lett. 98, 117601 (2007)",
        DOI: "doi.org/10.1103/PhysRevLett.98.117601",
        BibTex: `@article{PhysRevLett.98.117601, 
        title = {Low Relaxation Rate in Epitaxial Vanadium-Doped Ultrathin Iron Films}, author = {Scheck, C. and Cheng, L. and Barsukov, I. and Frait, Z. and Bailey, W. E.}, journal = {Phys. Rev. Lett.}, 
        volume = {98}, 
        issue = {11}, 
        pages = {117601}, 
        numpages = {4}, 
        year = {2007}, 
        month = {Mar}, 
        publisher = {American Physical Society}, 
        doi = {10.1103/PhysRevLett.98.117601}, 
        url = {https://link.aps.org/doi/10.1103/PhysRevLett.98.117601} 
        } 
        `,
        Citation: null
    },
    {
        Title: "Imaging of ferromagnetic resonance excitations in Permalloy nano structures on Si using scanning near-field thermal microscopy",
        People: ["R. Meckenstock", "I. Barsukov", "C. Bircan", "A. Remhoff", "D. Dietzel", "D. Spoddig"],
        Journal: "J. Appl. Phys. 99, 08C706 (2006)",
        DOI: "doi.org/10.1063/1.2171929",
        BibTex: `@article{10.1063/1.2171929,
        author = {Meckenstock, R. and Barsukov, I. and Bircan, C. and Remhoff, A. and Dietzel, D. and Spoddig, D.}, 
        title = "{Imaging of ferromagnetic-resonance excitations in Permalloy nanostructures on Si using scanning near-field thermal microscopy}", 
        journal = {Journal of Applied Physics}, 
        volume = {99}, 
        number = {8}, 
        pages = {08C706}, 
        year = {2006}, 
        month = {04}, 
        abstract = "{The investigated structures were Permalloy (Py) stripes of 3×0.3μm2 and a thickness of 24nm. Two samples with lattices of stripes of 2μm distance between the stripes and a lattice constant of 5μm are reported in this paper. One of the samples had crossed perpendicular lattices. The samples were prepared using standard lithography lift-off processes and comprised large arrays of at least 1000 stripes, such that enough material was available to perform conventional ferromagnetic-resonance (FMR) measurements. The overall anisotropy and resonance line behavior of the samples were determined by conventional FMR measurements. The origin of the FMR modes was then deduced locally resolved in single stripes using a scanning thermal microscope (SThM), which features a lateral resolution of 100nm and a temperature resolution of the order of a few millikelvins, mounted on a conventional FMR setup. The technique is based on the detection of the dissipated heat due to microwave absorption while in FMR. This setup provides an exact correlation of the SThM-FMR image and the simultaneously taken topography. In the crossed lattice sample the two resonance lines in the conventional spectra were identified as the parallel and perpendicular FMR excitations in each sublattice, respectively. A homogenous heating of a single stripe is observed while in FMR. In the single Py stripe lattice with external field parallel to the long axis of the stripe an additional resonance was found with slightly higher resonance field than the uniform mode. SThM-FMR measurements prove that this additional excitation is located at the polar edges of one stripe and is due to the round edges of each stripe and stray field effects.}", 
        issn = {0021-8979}, 
        doi = {10.1063/1.2171929}, 
        url = {https://doi.org/10.1063/1.2171929}, 
        eprint = 
        {https://pubs.aip.org/aip/jap/article-pdf/doi/10.1063/1.2171929/14965856/08c706\_1\_online.p df}, 
        }
        `,
        Citation: null
    }
];

export {publicationsArray}
    